### ISSUE TITLE
Characteristic illegal value

### ISSUE THREAD

**Issue by johnluber** [aqualinkd/homebridge-aqualinkd#6]
Been seeing this in the logs for a while now but hadn’t gotten around to reporting it.  This is with HB 1.3.5

[10/31/2021, 8:59:08 AM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number -27.78 exceeded minimum of -18. See https://git.io/JtMGR for more info.
[10/31/2021, 9:13:17 AM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number -27.78 exceeded minimum of -18. See https://git.io/JtMGR for more info.

**Comment by sfeakes** [comment]
I thought I fixed it in the latest release of Homebridge-aqualinkd, but while it's fixed for most temps, still their for spa. Thanks for reporting, and I'll update it soon, but it shouldn't;t be causing you any issues, just an annoyance in the logs.

**Comment by johntdyer** [comment]
Still getting this on HB 1.6.1 and homebridge-aqualinkd v0.2.1
```
          om the characteristic 'Target Temperature': characteristic was supplied illegal value: number 35 exceeded maximum of 6. See https://homebridge.io/w/JtMGR for more info.
[5/8/2023, 1:00:55 PM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 81 exceeded maximum of 40. See https://homebridge.io/w/JtMGR for more info.
[5/8/2023, 1:00:55 PM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 104 exceeded maximum of 40. See https://homebridge.io/w/JtMGR for more info.
[5/8/2023, 1:00:55 PM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 78 exceeded maximum of 72. See https://homebridge.io/w/JtMGR for more info.
[5/8/2023, 1:00:55 PM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 73 exceeded maximum of 72. See https://homebridge.io/w/JtMGR for more info.
[5/8/2023, 1:00:55 PM] [homebridge-aqualinkd] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 99 exceeded maximum of 72. See https://homebridge.io/w/JtMGR for more info.
```

**Comment by sfeakes** [comment]
It’s a bug / “feature” of homebridge.   The error reported is incorrect, but it won’t get fixed in homebridge.
Ultimately homebridge-aqualinkd fixes these issues before posting to HomeKit, but homebridge can only report/see these errors at a place before homebridge-aqualinkd fixes them.   So it’s a low priority to fix this

**Comment by sfeakes** [comment]
I just posted a new version that should surprise these message.
Please make sure to read the changelog, (if you update through homebridge-ui it will be displayed). You will need to edit your homebridge config.json.
